### ISSUE TITLE
Accessing Buffer in SlimerJS webserver

### ISSUE THREAD

**Issue by adampash** [laurentj/slimerjs#225]
Using the SlimerJS webserver, I'm trying to read an image from disk if it exists and respond with that image. Unfortunately I'm having trouble with encoding, and in particular, I can't get the image into base64 because I can't instantiate a new Buffer. 

Is it possible to make Buffer accessible inside SlimerJS? Or is there possibly an alternate approach that I'm not aware of?

**Comment by masi** [comment]
The problem is that you cannot write binary data with "fs". Any object (also Blob and ArrayBuffer) will be cast to a String before written to disk with fs.write(). Using the "b" option for binary data in fs.open or fs.write() doesn't help.

I have run into the same issue: you have to create a webpage and put the image as content, render the page, just to save an image.
