### ISSUE TITLE
How to use SlimerJS with a test runner.

### ISSUE THREAD

**Issue by justspamjustin** [laurentj/slimerjs#289]
On the homepage, it says,: "SlimerJS is useful to do functional tests"... However, I haven't found any way of using a test runner with SlimerJS besides through CasperJS. Is there any way to use something like mocha with Slimer?
Overall, I'm trying to write a suite of functional tests using SlimerJS. What is the best approach?

**Comment by laurentj** [comment]
Since you can write what you want in the script you give to SlimerJS, you can do what you want. So no best approach. And I don't know if mocha can run with Slimerjs. If you find users who use mocha with phantomjs, probably it can work with SlimerJS.

Please ask questions in the mailing list. Issues is for technical issue.
