### ISSUE TITLE
Cannot run multiple instances in parallel on Windows

### ISSUE THREAD

**Issue by jamesryanbell** [laurentj/slimerjs#290]
Hi

I am having some problems running multiple instances on Windows 7, this seems to be the same issue as [#18](https://github.com/laurentj/slimerjs/issues/18).

A new profile should be created on each instance if I understand the documentation properly but I am receiving an popup that says:

"SlimerJS is already running but is not responding. To open a new window, you must first close the existing SlimerJS proecss, or restart your system".

This works fine on Mac (Yosemite 10.10.1 (14B25)) so just seems to be a Windows issue.

Thanks,
James

**Comment by mariozivic** [comment]
Hi,

This is causing problems for us as well. We're trying to migrate from phantomjs but this is a show stopper at this moment.

Any thoughts if this will come in focus any time soon?

Regards,
Mario

**Comment by mariozivic** [comment]
Hi Laurent,

Found it! It seems that the problem is caused by the random seed in Windows batch files. This [link](http://stackoverflow.com/questions/19694021/random-generator-in-the-batch/19697361#19697361) says: Each instance of CMD.EXE initializes the random number generator upon startup using a seed that is derived from the current time with 1 second resolution. All CMD.EXE processes that launch within the same second will get identical random number sequences.

Since we start multiple slimerjs instances at the same time, we get a clash in __SLIMER_EXITCODEFILE as all instances started in the same second get the same file name and that causes (NS_ERROR_FILE_ACCESS_DENIED) [nsIFileOutputStream.init] (undefined ; line:26 col:0)

Does this make sense?

Regards,
Mario

**Comment by YousefED** [comment]
Seems to be related to #483 then

**Comment by mariozivic** [comment]
I'm 100% sure it is. We did a quick fix and removed the line setting __SLIMER_EXITCODEFILE as we don't need it but it would be nice to see a proper patch for starter batch file.

**Comment by laurentj** [comment]
@mariozivic Thank you for your investigation!!

So we have also the issue with profiles: two instances launched in the same second may have the same profile, so the second instance may display a dialog indicating that it is already started.

**Comment by MarkR42** [comment]
Great, is there some way we can roll the pid (of the shell) into the
exitcode filename?


Mark

**Comment by waza123x** [comment]
any news how to run multiple instances of slimerjs with same cookies without creating new profile ?
