### ISSUE TITLE
Return codes are not passed on with custom profiles

### ISSUE THREAD

**Issue by tsauerwein** [laurentj/slimerjs#333]
I am using `slimesjs-edge` in version 0.10.0-pre-2 which includes the fix for the return status (#50).

When I am using the default profile this fix works fine. But it doesn't work when using a custom profile (with the option `-profile profile-path`). The file `exitstatus` is created in the profile directory and also contains the right return value. But at the end, `0` is returned.

As a work-around I am currently directly reading the file `exitstatus`.

**Comment by abozhilov** [comment]
It needs additional work, to fix the issue with predefined profiles. We should recognize the profile directory in first place. Then delete exitstatus file in that directory if exists. Deleting file before launching slimer is very important, because if we skip that then in the next execution slimer crash, we would return invalid exit status, since the file `exitstatus` exists and its content is some previous status code. 
I will do the fix in next weeks, because I have no time right now.

**Comment by abozhilov** [comment]
I investigated the issue and there are some problems with implementing exit codes with custom profiles. As it's implemented if two processes are ran with same profile, there is no guarantee about the correctness of the exit code. 

We can create unique file somewhere and pass it to the xulrunner, when the process is finished we can read the exit code and delete that file.

@laurentj Please share your opinion, about the issue.

**Comment by laurentj** [comment]
I will create a temporary file for the exit code, and pass its name in an environment variable so SlimerJS could write in it.

**Comment by elemoine** [comment]
Thanks @laurentj for fixing this. It works for us!
