### ISSUE TITLE
Compatibility with node modules

### ISSUE THREAD

**Issue by laurentj** [laurentj/slimerjs#345]
SlimerJS should be able to load node modules, so it should supports "node_modules"  path

**Comment by laurentj** [comment]
It may fixes some issues with modules, as indicated in issue #337

**Comment by masi** [comment]
This would be nice, but adds some interesting issues the user must be warned. Just because you can require a Node module it doesn't necessarily work as the Node core modules are not available. And the module "fs" which is available in SlimerJS and Node are completely different. Additional wrappers might be necessary to ease running real Node modules.

This is not meant to discourage you from attempting to implement a Node compatible "require". IIRC you will also have to parse package.json to achieve full compatibilty. You may need to read the property "main" to resolve the include filename.

Cheers,
Masi

PS: I have started to wonder if it might not be "easier" in the long run to build SlimerJS (but also PhantomJS and TrifleJS) directly on Node. Perhaps not as Node module as it would require the user to compile the code, but in a way like CasperJS does. Make the CLI code an extension of Node and use Gecko only for the module "webpage".

**Comment by laurentj** [comment]
@masi thanks for the warning. There is the same issue with PhantomJS I guess.

>I have started to wonder if it might not be "easier" in the long run to build SlimerJS directly on Node

euh... no. definitively no. It will be difficult to fix API compatibilities with phantomJS....

**Comment by masi** [comment]
I am willing to contribute to Node shims. Can this be done from the outside (code distributed by NPM or Bower)? In PhantomJS I can easily modify/extend built-in classes (I have done this to get Promises to PhantomJS). Will the sandbox model of SlimerJS prevent this?
