### ISSUE TITLE
fs.size and fs.isFile crashes slimerjs silently

### ISSUE THREAD

**Issue by Ivanca** [laurentj/slimerjs#365]
Using fs.size crashes despite the file existing or not.
fs.isFile crashes when the file (or dir) does not exist.

Windows 8.1 64-bit, using the Windows build on the website (.zip)

**Comment by laurentj** [comment]
What do you call "crashes"? Is there a js error? Do slimerjs stop without message? What happen exactly?

**Comment by vans163** [comment]
It silent crashes, go test it.  Silent crash means that there is no error, nothing written to output, nothing crashes, but script halts.

**Comment by laurentj** [comment]
fs.size and fs.isFile (and other fs.isSomething) triggered an exception. fs.size because of an internal bad call, and fs.isSomething when the file didn't exist, although it should return false.

I didn't reproduced the crash on windows 7 64bits (I don't have Windows 8) : I had only error messages. Probably there is something that XulRunner/Firefox don't like when there is an exception on windows 8.

I fixed issues in fs.size and fs.isXXX . It should not trigger exception that crashes.

**Comment by silverhawk184** [comment]
Hello, I am having the same issue when calling isFile while using SlimerJS 0.9.6 (latest on website) and CasperJS 1.1.0-b5

**Comment by laurentj** [comment]
@silverhawk184 0.9.7 has not been released, and won't be in the future (not enough time). Next release will be 0.10. Try 0.10pre (master branch).
