### ISSUE TITLE
XUL deprecated

### ISSUE THREAD

**Issue by julmot** [laurentj/slimerjs#455]
I'm unhappy with PhantomJS as I want to get a test coverage of ES6 projects without transpiling them with Babel first. Therefore I'm interested in SlimerJS.

However, I'm afraid that the documentation describes
> Technically, SlimerJS is a XUL/JS application that is launched with Firefox.

Just yesterday I've got an email from Mozilla regarding this topic. A [compatibility lookup](https://compatibility-lookup.services.mozilla.com/) should be done for all addons as XUL will be deprecated in the end of 2017. Does this also mean that SlimerJS will be deprecated at this time? If so, are there any plans _currently_ to "upgrade" to a newer technology?

Also could anyone please describe in detail what "headless" in this sentence means?
> It is a tool like PhantomJs, except that it runs Gecko instead of Webkit, and it is not (yet) natively headless

Thanks in advance.

**Comment by MarkR42** [comment]
Hi,

I think the keyword here is "addons". Mozilla, as I understand it, plan to
deprecate, then remove XUL from addons. SlimerJS is not an addon, but
rather an alternative Mozilla front-end or application, so it may be able
to continue to use XUL.

However, SlimerJS's use of XUL is extremely minimal.

If XUL goes away completely, SlimerJS will need to adapt to whatever
alternative is used internally by the Firefox, Thunderbird UIs etc, but I
don't expect those to be rewritten in HTML5 any time soon.

---

"Headless" means not requiring a display / keyboard / mouse ("head") to
operate. PhantomJS will run without a display, SlimerJS will not. However,
on Linux it is easy to bypass this limitation by running SlimerJS under a
"fake" display program called "xvfb-run" which is shipped with nearly every
Linux distribution (although not usually installed by default).

You can also use xvfb-run to run SlimerJS invisibly if you do have a
dipslay, but don't want annoying "webpage" windows popping up all the time.

Mark

**Comment by laurentj** [comment]
@julmot as @MarkR42 said, SlimerJS is not an addon. It is a XUL application, **like Firefox**. Both run on top of Gecko, the Mozilla framework. So no chance to see XUL support removed in 2017 for applications. Mozilla plan to remove XUL support from Gecko in long term. It means that all the UI of Firefox will be rewritten with an other technology (html?). But no decisions has been made yet since it is a huge work.

Anyway, removing XUL does not mean the death of all internal API that allow to open windows, to monitor networking. So probably SlimerJS will continue to work. 

Or perhaps XUL will never be removed from Gecko, because of the huge work, and probably the best solution for Mozilla will be to switch to Servo, the new rendering engine they develop. This will be the end of SlimerJS of course.  But IMHO, it will not appear before 3-5 years...

**Comment by laurentj** [comment]
Please I prefer you ask questions on the mailing list. Github issues are for bugs or requests for improvements. Thanks.
