### ISSUE TITLE
An implementation of system.pid property

### ISSUE THREAD

**Issue by wskorodecki** [laurentj/slimerjs#473]
https://github.com/wskorodecki/slimerjs/commit/2943313b2c4aefc208edb02d575eee98d4ee21d2

For me it is returning correct process id of the main process (the root process in the process tree).
I don't know why you did not implemented it so far @laurentj :-) Did you miss it or maybe I missed something? Can I create a pull request?

**Comment by laurentj** [comment]
I did not implemented it because at the time I implemented the system module (commit 7d064dcf11fbb72d84bcb561c4ad545dcbaec6e0 on 2012-12-30 ), the processID was not implemented. It appears in Gecko only [1 year and a half later, on 2014-07-14](https://hg.mozilla.org/releases/mozilla-release/rev/0086975029c3) :-p. And I missed this improvement.

I'm ok for a PR :-)
