### ISSUE TITLE
Gecko version compat error when no graphical environment

### ISSUE THREAD

**Issue by dspruell** [laurentj/slimerjs#474]
### versions 

- SlimerJS: tested in 0.10.0 stable and 1.0.0-pre nightly
- Firefox: 46.0
- Operating system: Linux Ubuntu 14.04.4 LTS (trusty) 64-bit

### Steps to reproduce the issue

Linux system with no X11 environment.

- Install firefox (46.0+build5-0ubuntu0.14.04.2) from Ubuntu repo
- Unpack slimerjs 0.10.0 or 1.0.0-pre release
- Invoke slimerjs without use of xvfb

```
$ firefox -version
Mozilla Firefox 46.0
```
```
$ slimerjs -version
Innophi SlimerJS 0.10.0, Copyright 2012-2016 Laurent Jouanneau & Innophi
```

```
# Version in /opt/slimerjs-0.10.0/application.ini 
MaxVersion=46.*
```

```
# Versions in /usr/lib/firefox/application.ini 
Version=46.0
MinVersion=46.0
MaxVersion=46.0
```

### Actual results:

```
$ slimerjs
Gecko error: it seems /usr/bin/firefox is not compatible with SlimerJS. See Gecko version compatibility.
$ echo $?
1
````

However:

```
$ xvfb-run slimerjs 
script is missing
```

### Expected results:

No firefox compatibility error at runtime. Better behavior might be to attempt operation and inform user that failure occurred because of lack of graphical environment (Firefox compatibility output on exit is misleading/confusing).

**Comment by laurentj** [comment]
Well, because of no X environment, Firefox fails. On my debian, it displays :

```
$ firefox
Error: GDK_BACKEND does not match available displays
```

The exit code is "1".

If you run SlimerJS outside an X environment, there is the same error if you output them:

```
$ slimerjs --debug=true
Error: GDK_BACKEND does not match available displays
Gecko error: it seems /usr/bin/firefox is not compatible with SlimerJS. See Gecko version compatibility.
```

The slimerjs script output "Gecko error: it seems..." when the exit code is "1", because this is the exit code of Firefox when the version does not correspond.  No way to distinguish the reason of the fail of Firefox...

The only thing we can do is to improved the error message.
