### ISSUE TITLE
Trouble with 0.10.0

### ISSUE THREAD

**Issue by jefleponot** [laurentj/slimerjs#476]
Hi @laurentj,

Thanks for all your great work.

When I use slimerJS with casperJS selftest, there are 3 warnings and 2 errors : 

1. - **JavaScript strict warning**: resource://gre/modules/ProfileAge.jsm, line 202: ReferenceError: reference to undefined property times.reset
2. - **JavaScript strict warning**: resource://gre/modules/TelemetryEnvironment.jsm, line 488: ReferenceError: reference to undefined property this._environment._currentEnvironment.addons
3. - **JavaScript strict warning**: jar:file:///home/travis/build/casperjs/casperjs/engine/omni.ja!/components/httpd.js, line 796: ReferenceError: reference to undefined property this._stopCallback
4. - **JavaScript error**: resource://slimerjs/slimer-sdk/webserver.jsm, line 75: uncaught exception: 2147549183
5. - **JavaScript error**: resource://slimerjs/slimer-sdk/webserver.jsm, line 75: NS_ERROR_UNEXPECTED: Unexpected error'Unexpected error' when calling method: [nsIHttpServer::stop]

https://travis-ci.org/casperjs/casperjs/jobs/128888373

Regards,
jef

**Comment by laurentj** [comment]
I can't do nothing for 1 and 2. This is a Firefox issue.

**Comment by jefleponot** [comment]
:-)

**Comment by spyjo** [comment]
@laurentj @jefleponot with current git of casperjs and slimerjs, and latest firefox 55 nightly, I have this result with selftest:
FAIL 1297 tests executed in 73.378s, 1040 passed, 257 failed, 19 dubious, 46 skipped. 

Can you please run the selftest on your end and confirm if you have also this result ?

It seems a lot of failed are due to this one, like the point 5 posted above:
    uncaughtError: [Exception... "Unexpected error'Unexpected error' when calling method: [nsIHttpServer::stop]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: resource://slimerjs/slimer-sdk/webserver.jsm :: close :: line 78"  data: no] 

Others failed tests are mainly on formfill.js and pagestack.js
