### ISSUE TITLE
slimerjs 0.10.0 and Firefox MinVersion

### ISSUE THREAD

**Issue by jefleponot** [laurentj/slimerjs#479]
- SlimerJS: 0.10.0
- Firefox: 17.0.0 -> 39.0.0
- Operating system: linux 64

Hi @laurentj and everybody,

SlimerJS 0.10.0 is great and full of features but can I use it with old firefox browsers ?
Could I use it with firefox 24.5.0 ESR ?
More precisely, why have you fixed MinVersion to 38.0.0 in application.ini ?
https://github.com/laurentj/slimerjs/blob/v0.10/src/application.ini

Regards,
jef

**Comment by laurentj** [comment]
Mozilla Internal API change in each Firefox version. So some API disappear, other appear etc.. Since SlimerJS relies on those API, it can be compatible only with version of Firefox that provide the API it use.

Firefox 24 ESR is a very old version. I don't think Slimerjs 0.10.0 is working well on this version (even 0.9.6 but I didn't test).   
But you can try. If it doesn't work, you should use a previous version of SlimerJS.
