### ISSUE TITLE
error when exiting

### ISSUE THREAD

**Issue by YousefED** [laurentj/slimerjs#483]
When running 3 issues of slimerjs (with 3 different profiles) at the same time, writing the exit code in slExit.jsm can result in errors. Occassionally, foStream.init fails with an access denied error.

I have attached the file access log from Process Monitor. I'm not sure, but maybe the __SLIMER_EXITCODEFILE variable is accidentally shared by multiple instances?
### versions
- SlimerJS: 0.10.0
- Firefox: 45.0.1
  ![file log](https://cloud.githubusercontent.com/assets/368857/15398456/f6a85036-1de3-11e6-8e57-b685a5e9bcda.png)
- Operating system: Windows 8

**Comment by laurentj** [comment]
Well, in theory, [there is a different file](https://github.com/laurentj/slimerjs/blob/master/src/slimerjs.bat#L9) for each launch.

Or perhaps Window8 doesn't like this kind of code?

```
SET __SLIMER_EXITCODEFILE=%Temp%\slimerjs-exit-!Random!!Random!!Random!
```

Modify slimerjs.bat to show the value of this variable, and see if it is different for each instance.

**Comment by YousefED** [comment]
Thanks! I'm pretty sure it's usually different for each instance, as you can see the filenames in the screenshot.

Perhaps the issue is the random number generator: https://blogs.msdn.microsoft.com/oldnewthing/20100617-00/?p=13673

Maybe we could prevent the issue by also appending the time in milliseconds? (not a perfect solution)

---

Besides the race condition above, I guess another issue (looking at the problem on a different level) in slExit is that in case writing the exit file fails, slimerjs won't exit at all.

**Comment by laurentj** [comment]
>in slExit is that in case writing the exit file fails, slimerjs won't exit at all.

Yes, it should exit in any case...

**Comment by mariozivic** [comment]
C/P from #290 : It seems that the problem is caused by the random seed in Windows batch files. This [link](http://stackoverflow.com/questions/19694021/random-generator-in-the-batch/19697361#19697361) says: Each instance of CMD.EXE initializes the random number generator upon startup using a seed that is derived from the current time with 1 second resolution. All CMD.EXE processes that launch within the same second will get identical random number sequences.
