### ISSUE TITLE
Signature should be a plain detached signature

### ISSUE THREAD

**Issue by graingert** [laurentj/slimerjs#487]
Currently it's not possible to check the signature of slimerjs

It should be possible to do:

```
ENV GPG_KEYS 7D8D8DF97FC557D9F287B1A6FB076108DBC76C05
ENV SLIMER_VERSION 0.13.11
RUN    curl -fSL https://download.slimerjs.org/releases/$SLIMER_VERSION/slimerjs-$SLIMER_VERSION.zip -o slimerjs.zip \
                 https://download.slimerjs.org/releases/$SLIMER_VERSION/slimerjs-$SLIMER_VERSION.zip.asc -o  slimerjs.zip.asc \
    && export GNUPGHOME="$(mktemp -d)" \
    && gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys "$GPG_KEYS" \
    && gpg --batch --verify slimerjs.zip.asc slimerjs.zip \
    && rm -r "$GNUPGHOME" slimerjs.zip.asc \
    && unzip slimerjs.zip -d /root/ \
    && rm slimerjs.zip
```

However the .asc file is not a detached signature, <del>and the key DBC76C05 has not been uploaded to [a keyserver](https://pgp.mit.edu/pks/lookup?search=0x7D8D8DF97FC557D9F287B1A6FB076108DBC76C05&op=vindex&fingerprint=on). <del> I found it on your website, and uploaded it to [pgp.mit.edu](https://pgp.mit.edu/pks/lookup?search=0x7D8D8DF97FC557D9F287B1A6FB076108DBC76C05&op=vindex&fingerprint=on).

**Comment by graingert** [comment]
@laurentj you can create .sha1 and .sha1.asc files if you want people to be able to verify the checksum

**Comment by laurentj** [comment]
what should contain these files ? Do you mean ".sha1" or "slimerjs.zip.sha1"?

**Comment by graingert** [comment]
out of interest, how does your CI work? Can you run on travis?

**Comment by laurentj** [comment]
>slimerjs-$SLIMER_VERSION.zip.sha1.asc files if you want people to be able to verify just the checksum

Well, they can already verify the checksum. What's wrong with [the method I give on this page](https://slimerjs.org/checksum.html)? (except the key which was not uploaded on pgp.mit.edu, thank you :-)) 

Note: I don't know very well all possibilites of gpg

> out of interest, how does your CI work?

I have a [Strider CD](https://github.com/Strider-CD/strider) instance, that run simple bash scripts.  One of them launches the buildpackage.sh and launches sha256sum on zip. Note that my CI doesn't launch unit tests (yes, this bad, but I need to upgrade my server in order to launch them in a secure way, in a docker container for instance...)

> Can you run on travis?

This is not acceptable for me to build packages on travis and to download them (with signatures) to my server : I don't want to give an ssh access on my server to an external service to allow it to push packages. The only thing I could accept with travis is to launch unit tests. But I didn't find time yet to configure a travis script (contributions are welcomed ;-))

**Comment by graingert** [comment]
I just don't see the point in using shasum for only one file

**Comment by graingert** [comment]
> This is not acceptable for me to build packages on travis and to download them (with signatures) to my server : I don't want to give an ssh access on my server to an external service to allow it to push packages. The only thing I could accept with travis is to launch unit tests. But I didn't find time yet to configure a travis script (contributions are welcomed ;-))

Of course, I don't expect you to sign them on Travis! I just want to know what you run to generate the sigs etc.

**Comment by laurentj** [comment]
For next releases, some .sha256 files will be generated containing only sha256 sum...
