### ISSUE TITLE
SlimerJS Seg Faults on SVG xlink:href 404 not found

### ISSUE THREAD

**Issue by EWhite613** [laurentj/slimerjs#514]
### versions 

- SlimerJS: 0.906.2 
- Firefox: 48.0, (various)
- Operating system: Mac OSX, Linux (Untested on Windows)

### Steps to reproduce the issue
* Using simple slimerJS script:
```
'use strict'
var system = require('system')
var page = require('webpage').create()
var url = system.args[1]
page.viewportSize = {
  width: 1024,
  height: 5000
}

page.open(url)
```

* Visit https://jsfiddle.net/2v9eq70x/
  * `slimerjs slimerjsScript.js https://jsfiddle.net/2v9eq70x/`

Returns: 
`line 173: 42441 Segmentation fault: 11  "$SLIMERJSLAUNCHER" -app "$SLIMERDIR/application.ini" $PROFILE -no-remote "$@" 2> /dev/null`

### Expected results:

Shouldn't segmentation fault.
* Using this example website https://jonathantneal.github.io/svg4everybody/. 

  * opening with the script : `slimerjs slimerjsScript.js https://jonathantneal.github.io/svg4everybody/`. 
    * clicking on `Add an External SVG`. Results in `<use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="demo.svg#pencil"></use>` which does not crash. I assume since it is not a 404 link.

### Notes
This issue ends up breaking quite a few of my apps where I use https://github.com/jonathantneal/svg4everybody . Not entirely sure why they're assumingly 404'd on the images in SlimerJS but I've never been able to debug as I always Seg Fault. And end up with some Apple Crash Report.

**Comment by wskorodecki** [comment]
I can confirm that this problem occurs also in:

- SlimerJS: 1.0.0
- Firefox: 41.0.2, 47
- Operating system: Ubuntu 15.04 64bit

**Comment by laurentj** [comment]
This is an issue of the rendering engine, so an issue with Firefox, not SlimerJS.

**Comment by EWhite613** [comment]
@laurentj You lost me. I don't understand how's this a Firefox issue? Firefox deals with https://jsfiddle.net/2v9eq70x/ fine (404s as it should), whereas SlimerJS seg faults...

I ask because I have no information to open up an issue on https://bugzilla.mozilla.org/

**Comment by EWhite613** [comment]
Mozilla bug created here: https://bugzilla.mozilla.org/show_bug.cgi?id=1292185

**Comment by laurentj** [comment]
> you lost me

SlimerJS is just "few" Javascript files on top of Firefox. It doesn't change anything in the rendering engine. And your issue is a rendering engine issue. So, from my point of view, this is a Firefox issue. And I don't know why it works well in Firefox. Probably there is something that is missing (in configuration?) to process 404 links in SVG in SlimerJS (but I don't know what), but Firefox should not crash anyway.

I just see also that you use an unknow official SlimerJS version, probably a very old one (0.9??), not tested with recent Firefoxes.

And about your Mozilla bug : SlimerJS is not bundled with XulRunner anymore, since XulRunner does not exist anymore. Recent versions of SlimerJS need Firefox, not XulRunner.

**Comment by EWhite613** [comment]
Doesn't running `firefox.exe -app *.ini`  [Start a new process running the XULRunner application](https://developer.mozilla.org/en-US/docs/Mozilla/Command_Line_Options#-app_.2Fpath.2Fto.2Fapplication.ini)?

I realized that after I posted the bug I should've tested with the source rather than the [npm package] (https://www.npmjs.com/package/slimerjs). Which I did later (resulting in the same issue) , but @wskorodecki already beat me to the punch with his confirmation.
