### ISSUE TITLE
Doesn't work with latest version of firefox

### ISSUE THREAD

**Issue by jon64digital** [laurentj/slimerjs#519]
### versions 

- SlimerJS: 
- Firefox: 
- Operating system: 

### Steps to reproduce the issue

Run casperjs from command line

### Actual results:

![capture](https://cloud.githubusercontent.com/assets/2878796/17776333/f5767cc6-6553-11e6-9cd3-e2697547f862.PNG)

**Comment by wskorodecki** [comment]
As you see in the dialog window you must raise maxVersion. You can do it by editing the following file:
https://github.com/laurentj/slimerjs/blob/master/src/application.ini
Note that you may encounter some new errors, because higher versions are not officially supported (yet).
Or use SlimerJS v0.10 which supports Firefox 46.

**Comment by jon64digital** [comment]
Yeah, I found that eventually and got different errors, but thanks for trying.

**Comment by KevinGrandon** [comment]
@jon64digital - Have you tried the latest code? It might be fixed here: https://github.com/laurentj/slimerjs/pull/513

**Comment by laurentj** [comment]
@jon64digital it seems also you are using an old SlimerJS version. Please upgrade. 0.10.1 will be released soon and will be compatible with Fx 48.
