### ISSUE TITLE
Crash Annotation GraphicsCriticalError

### ISSUE THREAD

**Issue by danilkinanton** [laurentj/slimerjs#566]
xvfb-run --auto-servernum --server-num=1  slimerjs -P user script.js

`Crash Annotation GraphicsCriticalError: |[0][GFX1]: Unknown image format 16 (t=0.32756) [GFX1]: Unknown image format 16`
Please help me. What's the matter?

SlimerJS 0.10.2 (npm)
Mozilla Firefox 50.1.0
os: Ubuntu 14.04.3 LTS

**Comment by corderogerardo** [comment]
Would you describe more your Server Environments please?
Example:
CentOS 7 over Digital Ocean or AWS.
Please check your video drivers and display more information about it.
For example use this commands: 
lspci | grep -i vga
sudo lshw -C video

I tested with two servers and I got this results.
I have the same problem as you over Digital Ocean and Ubuntu 16.04. 
But that doesn't stop the steps executions of my script. All the steps are done as hoped. 
That message is just a little annoying.

I got only 24 steps done of 33 because I do this.die() when an email option exists over the website. It is just a test.
[error] [phantom] I clicked on the mail option 
I clicked on the mail option 
[info] [phantom] Step anonymous 24/33: done in 34054ms. 
Crash Annotation GraphicsCriticalError: |[0][GFX1]: Unknown image format 16 (t=2.1859) |[106][GFX1]: Unknown image format 16 (t=33.8704) |[107][GFX1]: Unknown image format 16 (t=35.0711) |[108][GFX1]: Unknown image format 16 (t=35.7489) |[109][GFX1]: Unknown image format 16 (t=35.9241) |[95][GFX1]: Unknown image format 16 (t=17.5981) |[96][GFX1]: Unknown image format 16 (t=17.6137) |[97][GFX1]: Unknown image format 16 (t=17.6309) |[98][GFX1]: Unknown image format 16 (t=17.6479) |[99][GFX1]: Unknown image format 16 (t=17.6637) |[100][GFX1]: Unknown image format 16 (t=17.7473) |[101][GFX1]: Unknown image format 16 (t=29.3025) |[102][GFX1]: Unknown image format 16 (t=29.3524) |[103][GFX1]: Unknown image format 16 (t=30.5557) |[104][GFX1]: Unknown image format 16 (t=31.5121) |[105][GFX1]: Unknown image format 16 (t=32.6697) [GFX1]: Unknown image format 16

I have a second Dedicated Server which doesn't have the error Crash Annotation GraphicsCriticalError: |[0][GFX1]: Unknown image format 16 (t=0.32756) [GFX1]: Unknown image format 16.
Everything works nice over that server and I can see every step. SlimerJS provide good stability and always work, it didn't crash as Phantomjs does.

Over the dedicated server, I install the drivers for that server. And did a configuration over the xorg.conf file.

**Comment by danilkinanton** [comment]
`lshw -c video                             *-display UNCLAIMED`
      ```
 description: VGA compatible controller
       product: GD 5446
       vendor: Cirrus Logic
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 00
       width: 32 bits
       clock: 33MHz
       capabilities: vga_controller
       configuration: latency=0
       resources: memory:f0000000-f1ffffff memory:f2000000-f2000fff memory:f2010000-f201ffff
```

**Comment by corderogerardo** [comment]
You can try with this example of a xorg.conf file http://xpra.org/xorg.conf 

If fails write it here I will give you my xorg.conf file that works over my servers server.

**Comment by danilkinanton** [comment]
It did not help!
I have placed xorg.conf to /etc/X11/ and restarted gdm.
The problem still exists.

**Comment by laurentj** [comment]
This is probably an issue with Firefox, not SlimerJS.

Try to launch Firefox with xvfb instead of SlimerJS, to see if the bug appears with Firefox only.

Did you install Firefox with Ubuntu package, or did you get the vanilla package from Mozilla (getfirefox.com)?
Try with both installation and tell us what are the results

**Comment by danilkinanton** [comment]
I have installed firefox-37.0.2 from wget and now I got another error....
` xvfb-run -a firefox http://google.com ` 
```
(process:3717): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
Xlib:  extension "RANDR" missing on display ":116".
```

**Comment by laurentj** [comment]
>firefox-37.0.2

version 37? the latest is 50.0.2.

For the last error, it seems it is a bad environment/xvfb configuration (google has lot of solutions..). For example, try something like `export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/` before launching xvfb. Be sure also you have installed all graphical drivers, all libraries needed by Firefox etc..

**Comment by corderogerardo** [comment]
You can hide the message, put this (| grep -v GraphicsCriticalError) at the end of the xvfb-run casperjs script.js | grep -v GraphicsCriticalError. I did not have any error working with Ubuntu Vivid. But with Ubuntu Xenial I can reproduce the same error in 2 servers.
