### ISSUE TITLE
let is a reserved identifier

### ISSUE THREAD

**Issue by thany** [laurentj/slimerjs#567]
### versions 

- SlimerJS: 0.10.2
- Firefox: ?
- Operating system: Windows 10

### Steps to reproduce the issue
Execute a script that includes a `let` statement. For example:
```
let output = "";
```
Simple as that.

### Actual results:
```
Mozilla/5.0 (Windows NT 10.0; WOW64; rv:38.0) Gecko/20100101 SlimerJS/0.9.6 ERROR
  SyntaxError: let is a reserved identifier
```
I'm not using let as an identifier. I'm using it exactly and only as intended.

### Expected results:
Script should execute just fine. It's a perfectly valid statement.

**Comment by thany** [comment]
I don't know what the bug report template means by Firefox version. It's whatever SlimerJS comes with. My browser is Firefox 50, but something tells me it's not using my installed browser, but ships with a separate Gecko instance.

**Comment by thany** [comment]
Clearly it comes with *some* version of Firefox. The error says, right there, it's Firefox 38 in the UA string. I don't have that version installed anywhere, so it must be doing its own thing.

I don't see why this issue is invalid, tbh. In the end, it's an error that's not supposed to happen.

**Comment by laurentj** [comment]
I mark this issue as invalid because:

# I cannot reproduce the issue. I tried with Firefox 38 + SlimerJs 0.9.6 and 0.10, and it works for me
# there is no reason that it does not work, as the `let` keyword was implemented many years ago into Firefox and used everywhere into its source code (although `let` is exposed to web content only since Firefox 44)
# Anyway, if it doesn't work, this is an issue with Firefox, not SlimerJS, as the javascript engine is provided by Firefox, not by SlimerJS
# last point: the user agent says "0.9.6" (although you said you installed 0.10). Slimerjs 0.9.6 is not maintened anymore.
