### ISSUE TITLE
Does SlimerJS support ES6 syntax?

### ISSUE THREAD

**Issue by pitymaia** [laurentj/slimerjs#570]
### versions 

- SlimerJS: Innophi SlimerJS 0.10.2

- Firefox: 50.1.0

- Operating system: Ubuntu 15

Hi I try to test ES6 and AngularJS code with Karma. SlimerJS docs says that it implement most of ES6, but when I try to run my code it crashes at the first "class" or "let" it founds.

Here is the trace:

```
Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 SlimerJS/0.9.6 ERROR
  SyntaxError: class is a reserved identifier
```

And:
```

Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 SlimerJS/0.9.6 ERROR
  SyntaxError: let is a reserved identifier
```

I misunderstanding the docs and SlimerJs don't support ES6 syntax or is another problem?

Thanks.

**Comment by laurentj** [comment]
In a web page or in your slimerjs script?

**Comment by laurentj** [comment]
Note that your are running Gecko 38, aka Firefox 38. At the time of the release of Firefox 38, I guess that it didn't supports all ES6 features in web pages.

Please use Slimerjs 0.10 with Firefox 50.

**Comment by laurentj** [comment]
Strange, you have the same issue as #567: your error message indicates the same old Firefox version, and it doesn't correspond to what you write.

Please tell us the version returns by the `slimer.geckoVersion` property from your script.

**Comment by corderogerardo** [comment]
I was able to use IPv6 with Slimer because of this mozilla bug report https://bugzilla.mozilla.org/show_bug.cgi?id=201685.

Resume. 
All you need to do is enable a domain and configure it with your proxy server, so you can do the following: 
**This way Works.**
casperjs script.js --engine=slimerjs --disk-cache=no  --proxy=proxyv6-2.domain.com:3128 --proxy-auth=user:pass --proxy-type=socks5 | grep -v GraphicsCriticalError . 

_This way doesn't work._
You can't use the way --proxy=[ipv6]:2000 because it doesn't work, read the bugzilla report for more information.

**Comment by pitymaia** [comment]
Hi, 

I just follow your link to the other issue and test the slimerjs with a file only using this commands:

`let v = slimer.geckoVersion;
console.log('version: ' + v.major + '.' + v.minor + '.' + v.patch);`0

It works and give me this:

`version: 50.1.0`

The slimerjs window shows the version: **0.10.2**
When I try to run slimer with **karma** it windows shows the versions: **0.9.6**
I dont notice this before. I am running a headless version with  **xvfb-run**.

The **karma-slimerjs-launcher** maybe is the bad guy here as you suggested in the other issue.
Now I have an indication of the problem and know that the SlimerJS works with "let" ES6 sintax, I go to look into it.

Thanks for the help.

**Comment by laurentj** [comment]
Ok so I can close the issue. Thanks for your feedback.
