### ISSUE TITLE
/srv/var/slimerjs/slimerjs: line 167:    48 Killed

### ISSUE THREAD

**Issue by RyanBertrand** [laurentj/slimerjs#571]
### versions 

- SlimerJS: 0.10.2
- Firefox: 50
- Operating system: ubuntu:14.04

### Steps to reproduce the issue
Launch AWS instance with Linux AMI and run via Docker.  SlimerJS exits after ~10 minutes.    

### Actual results:
Exits after printing:
```/srv/var/slimerjs/slimerjs: line 167:    48 Killed                  "$SLIMERJSLAUNCHER" -app "$SLIMERDIR/application.ini" $PROFILE -no-remote "$@"```

### Expected results:
Shouldn't exit after ~10 minutes

**Comment by MarkR42** [comment]
Probably the process is killed by the Linux out of memory killer, or runs out of address space or memory. It could also exceed the VM resource limits or container resource limit. Look on the kernel log (or maybe container log?) to see what's happened.

The underlying cause is possibly your script failing to close something or clean up. Or you maybe load an extremely large web page.

I've found that if you're making a crawler which just scans random sites, some pages are likely to use too much memory. You will need to handle this in your application somehow.

**Comment by RyanBertrand** [comment]
Yes, I think that is what is happening here. It looks like Firefox is dying after the container hits the 100% memory for a bit of time.  I will close this as it's unrelated to SlimerJs. Thanks @MarkR42 !
