### ISSUE TITLE
NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIProperties.get

### ISSUE THREAD

**Issue by txt3rob** [laurentj/slimerjs#629]
### versions 

- SlimerJS: 10.0.3
- Firefox: 52.2.0esr
- Operating system: Ubuntu 17

### Steps to reproduce the issue
```
xvfb-run -a /home/slim/slimerjs/slimerjs --debug=true  /home/slim/slimerjs/test.js
```
### Actual results:
```
JavaScript error: jar:file:///opt/firefox/omni.ja!/components/XULStore.js, line 66: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIProperties.get]
```
### Expected results:

Starting Server

**Comment by txt3rob** [comment]
like magic somehow it's started to work on it's own! no command changes or script changes so going to close this.

**Comment by jtprobst** [comment]
For future reference. I had the same issue and for me the probable cause was that I had another instance of slimerjs already using that profile. Note that there is a lock file in the profile so the first instance of slimerjs which is started obtains the lock, and the second slimerjs instance attempting to access the same profile stays blocked and prints the error from above.

Probably your other slimerjs instance was stopped, killed, crashed, or shut down otherwise so it started working all of a sudden.
