### ISSUE TITLE
Flash content doesn't load

### ISSUE THREAD

**Issue by iKethavel** [laurentj/slimerjs#663]
### Versions 

- SlimerJS: 0.10.3
- Firefox: 52.0.2 (64-bit)
- Operating system: Windows 10 Pro

### Steps to reproduce the issue
Paste code and run

### Actual results:
Doesn't load flash content

### Expected results:
Successfully loaded flash content

```
const pageFactory = require('webpage');   // factory for webpage objects
const page = pageFactory.create();    // main page which loads data pages at angel.co/jobs
const FLASH_TEST = 'https://www.adobe.com/swf/software/flash/about/flashAbout_info_small.swf';
const CHIBI_URL = 'http://www.dolldivine.com/chibi-maker.php';

page.viewportSize = {width: 1366, height: 768};
page.open(CHIBI_URL, function () {
    console.log(`opened`);

    setTimeout(function () {

        page.evaluate(function () {
            window.scrollBy(0, 200);
            document.querySelector('embed').click();
        })

        page.render('screenshot.png')

    }, 10000)

});
```

**Comment by laurentj** [comment]
Flash content is probably loaded, but it doesn't appear in screenshots. See the FAQ: https://docs.slimerjs.org/current/faq.html#i-don-t-see-flash-content-when-i-take-a-screenshot-with-render

**Comment by iKethavel** [comment]
But in browser preview is also doesn`t show?

**Comment by laurentj** [comment]
If the flash content is not shown in the window opened by SlimerJS, probably it's because:

- flash is not installed correctly. Open the same page with Firefox on the same machine
- Firefox blocks flash content by default since few versions. There is probably a preference to set in the profile (I don't remember which preference). Create profile and set the preference in the prefs.js file. https://docs.slimerjs.org/current/configuration.html#profiles.

Anyway, even if Flash content is loaded correctly, it won't appear in a screenshot because of a bug in Firefox (see FAQ).

**Comment by iKethavel** [comment]
> Anyway, even if Flash content is loaded correctly, it won't appear in a screenshot because of a bug in Firefox (see FAQ).

In that flash app has the opportunity to save image, can i do that with slimerjs?
( http://www.dolldivine.com/chibi-maker.php )

**Comment by laurentj** [comment]
Probably. Never tested.
