### ISSUE TITLE
Arch/Manjaro package manager can not download from download.slimerjs.org

### ISSUE THREAD

**Issue by slrslr** [laurentj/slimerjs#720]
Hello, [the issue is described there](https://forum.manjaro.org/t/pamac-build-fails-to-dl-package-curl-60-ssl-certificate-problem-unable-to-get-local-issuer-certificate/46486).

You may check the subdomain on these sites:
https://www.geocerts.com/ssl-checker
https://www.ionos.com/tools/ssl-checker
https://www.sslchecker.com/sslchecker
https://decoder.link/sslchecker/download.slimerjs.org/443

it may tell more details..

**Comment by laurentj** [comment]
The certificates are configured by certbot, the certificates manager by Let's encrypt and my server is configured to use the fullchain.pem file provided by certbot. If there is an issue, this is an issue into certbot.

But for me, there is no issue. The server does not sent the root certificate because it does not need to. a TLS/SSL client should have all root certificates. For example, Firefox have its own certificate store, and contains the root certificate used by certbot, this is why it does not complain.

If a software complains about a root certificate that is missing, this is because the root certificate is not installed in the certificate store of the operating system (or in its own certificate store if it have one).

So the solution is to install root certificates onto your machine.  See https://letsencrypt.org/certificates/

On debian/ubuntu, it should be stored into /etc/ssl/certs.
