### ISSUE TITLE
SlimerJS cannot capture flash content

### ISSUE THREAD

**Issue by Acconut** [laurentj/slimerjs#81]
> SlimerJS is able to load flash content if the Flash plugin is installed

I have an Ubuntu server running on which slimer is installed and can be executed using `xvfb-run`. But when I try to load a [site](http://www.dhs.state.il.us/accessibility/tests/flash/video.html) using flash and render it into an image I just get the view as there wouldn't be a flash plugin.

I've tried to install `flashplugin-installer` and also `browser-plugin-gnash` and run slimer using `--load-plugins=true` (does this option even exist?) but I just get some errors/warnings: 
[https://gist.github.com/Acconut/f457d59361b3f2704d60](https://gist.github.com/Acconut/f457d59361b3f2704d60)

Before I installed `browser-plugins-gnash` there was a note about installing flash in the image.

So how do I use slimer with flashcontent. Any help appricated.
Thanks!

**Comment by neopostmodern** [comment]
I just used slimerjs master against FF42 on Ubuntu 15.10 and successfully took a screenshot of Flash content. So it seems like the FF bugs were solved. (I _might_ be using [FreshPlayer](http://www.webupd8.org/2015/01/fresh-player-plugin-sees-new-release.html). I'm not really sure, but maybe that's important?)

Running it through `xvfb-run` doesn't work still (no flash content) - has anybody else figured how to solve that?

**Comment by puravida** [comment]
@neopostmodern But did you confirm that Flash VIDEO would capture? I suspect that it would not. 

I spent the last 30 hours working on this, and I can get it installed and detected and showing the latest Linux supported version v11.2, but it will not capture any Flash video to a screenshot image. 

I tested on CentOS 7.2, Ubuntu 14.04, and Fedora 24, all with the same result. I even spent many hours working through painfully installing FreshPlayer on Fedora 24 and confirmed that it showed v22 Flash was installed and while it would play all Flash video/content in Firefox directly and with slimerjs loading URL w/ Flash (if taking a screenshot using import method mentioned by @g0morra ), the screenshot render would be missing the Flash video content.

The external desktop screenshot method is unacceptable for my use case, as it requires an unreasonable delay on every URL, since it would be impossible to have any idea when the page might be finished loading.

**Comment by puravida** [comment]
For test purposes, to consider Flash successfully captured, you need to be able to capture the Flash version shown on this [Adobe Flash video test page](https://www.adobe.com/swf/software/flash/about/flashAbout_info_small.swf).

**Comment by puravida** [comment]
Also, when I took a screenshot of the desktop, there was a slimerJS logo in the upper left corner. Just in case I use some version of workaround using the desktop, could somebody tell me how to disable that logo from displaying?? Thanks! :)

**Comment by laurentj** [comment]
@puravida yours issues have been already discussed in github issues and in the mailing-list. And the [documentation about render()](https://docs.slimerjs.org/current/api/webpage.html#webpage-render) talks about some of them. I also updated [the Faq](https://docs.slimerjs.org/current/faq.html). Please read these pages.

**Comment by puravida** [comment]
@laurentj Thanks for the notes. I actually did see the related github issues and two related Mozilla bugs. I even saw that note in the render documentation but had forgotten about it since that was before I started testing weeks ago.

I didn't think to check back on the FAQs. I just now saw the note about the slimer logo and Flash. Thank you.

So, the confusion for me was that I saw multiple people stating that Flash works with slimerjs and that it had been fixed. These were mentions in this github project and also around the web. In reality, slimerjs supports Flash in the specific case of wmode=transparent, which most sites do not use. So, in browser automation testing, it can be made to work, but in "the wild", it is likely to fail most of the time. I realize that it is out of your control, but that is unfortunate.
